version: "3.8"

services:
  segment_anything_model:
    container_name: segment_anything_model
    image: heartexlabs/label-studio-ml-backend:sam-master
    build:
      context: .
      shm_size: '4gb'
      args:
        TEST_ENV: ${TEST_ENV}
    deploy:
      resources:
        limits:
            memory: 16G
        reservations:
            memory: 8G
            # Add this to pass through 1 GPU 
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    environment:
      # Change this to your model name: MobileSAM or SAM
      SAM_CHOICE: "SAM"
      LOG_LEVEL: "DEBUG"
      # Set NVIDIA_VISIBLE_DEVICES to "2" to use GPU ID 2
      NVIDIA_VISIBLE_DEVICES: "2"
      # Configuration for the model server workers and threads
      WORKERS: 1
      THREADS: 8
      # Specify the model directory (usually does not need changes)
      MODEL_DIR: "/data/models"

      # Label Studio URL and API key for integration
      LABEL_STUDIO_HOST: "http://172.16.1.16:8080/"
      LABEL_STUDIO_ACCESS_TOKEN: "3a229ce5682afbba84c16784495da8d0cadcb044"

    ports:
      - 9091:9090
    volumes:
      - "./data/server:/data"
